### ISSUE TITLE
[Android, ESP] s-meter

### ISSUE THREAD

**Issue by rudehardware** [VanceVagell/kv4p-ht#108]
adding signal strength meter will be nice 👍

**Comment by VanceVagell** [comment]
Thanks for the idea! We can do this when the kv4p HT has been built with an SA818-V, which supports RSSI info. The DRA818-V does not. So we should detect which module is being used, and enable an S-meter if the module supports it.

**Comment by BillH63** [comment]
According to this document https://www.dorji.com/docs/app/ADW1016_DRA818U_DRA818V_Source_Codes_For_PIC.pdf RSSI is supported in the DRA818 series.

**Comment by VanceVagell** [comment]
Relevant part of API:

3.7） Read RSSI
Format: RSSI?
Reply: RSSI=X
“X”:
Value of RSSI, from 0 to 255, unit 1dB

Our dra818 library has this built in as rssi(), but it gives us the raw return (which will be 0-255).

**Comment by VanceVagell** [comment]
S-meter is implement and will be in the next release.
