### ISSUE TITLE
SSB Mode - 

### ISSUE THREAD

**Issue by N7XBJ** [VanceVagell/kv4p-ht#111]
Would this be possible if so it would be pretty much the ONLY handheld SSB device out there - You can do it with a Quansheng UV5A but it is DSB works but is NOT the best solution - I found this - To program a DRA818V module into SSB (Single Sideband) mode, you need to send specific AT commands through its UART interface, typically using a serial communication protocol, setting the "mode" parameter to "SSB" within the command string; essentially, you are configuring the module to operate in SSB mode by sending these commands to it via a serial connection" IS it possible?

**Comment by VanceVagell** [comment]
Thanks for the idea! Unfortunately the radio module we're using is strictly FM, so this won't be possible. But cool idea.
