### ISSUE TITLE
[Android] APRS debug mode to display decoded raw strings in display

### ISSUE THREAD

**Issue by gx1400** [VanceVagell/kv4p-ht#116]
Add a slider in the settings menu for Debug mode

Debug mode would print the raw decoded string in the text window so you can see how values are being parsed

**Comment by VanceVagell** [comment]
Ended up just always printing non-decodable messages with a "Raw:" prefix, rather than adding a setting for this. Over time we should try to support more and more message types so we see fewer of these spammy "raw" ones, but at least we're not dropping data now.
