### ISSUE TITLE
RX audio issue

### ISSUE THREAD

**Issue by LamaBleu** [VanceVagell/kv4p-ht#123]
Hi,
First thank you for this nice project, really interesting ! We (a group of 5 french hams) decided to try !  
Since I'm not on discord, opening a new issue here.  

We purchased the kits early november to PCBWAY (PCB + assembly).   
PCB layout date is 2024-10-23 (I think it's v1.6). No problem to program the units (both Arduino IDE, and flashing from app worked well).  
We are facing an issue on all units regarding the RX. The squelch is not working at all, and we have a permanent noisy sound while RXing. If I try to transmit from a remote transceiver, I can hear the DTMF, but the voice is really faint.  
The TX part is perfectly working, both voice and APRS (we decoded from SDR).  

Uploaded a 10 seconds audio sample to give you a better idea : we can clearly hear the DMTF when I transmit in the middle of record ([MP3 link](http://www.lamableu.net/files/kv4p_audio.mp3)).   

We tried several versions of the Android app, and firmware, always same issue.
I can't determine if we are facing RF noise (also tested on dummy load, same problem), or sampling issue on the I2S side.  
Do you have an idea or previous reports about this issue ?
Thank you for your answer !  
73's
![kv4p_kit](https://github.com/user-attachments/assets/cc095b96-f478-4489-b767-ff02d7a11789)

**Comment by VanceVagell** [comment]
Hi there! This issue sounds like the ESP32 is not providing rx audio bytes to the Android app fast enough, so the audio is dropping out intermittently, but it's hard to say for sure.

I'd try an ESP32 from a different manufacturer to see if that helps, maybe you got a bad batch.

I definitely recommend you come into the Discord and ask this in the #general channel, there are 1000+ hams in there, and are always helping each other solve problems like this! If you change your mind, here is the link:

https://discord.gg/Ev9R9uFeCq
