### ISSUE TITLE
Discord invite on kv4p.com (and elsewhere) has expired

### ISSUE THREAD

**Issue by kalendar** [VanceVagell/kv4p-ht#133]
I'd like to join the Discord but the invitation link has expired.  Please create a new permanent invitation link. Instructions here - https://www.youtube.com/watch?v=t4Lxu5WsL8E

**Comment by VanceVagell** [comment]
Hi David, you may be seeing a very old version of the web pages. I replaced
these invites with permanent ones more than a month ago. please try
shift+refresh on the page (to clear the cache) and see if it works
afterwards.

**Comment by kalendar** [comment]
Thanks, Vance. I cleared the cache, but it's the same invitation link there as before - https://discord.gg/WKTEhuEZhp

![Screenshot 2024-12-10 at 3 16 19 PM](https://github.com/user-attachments/assets/bbb52181-63a3-49bc-8fa6-58820f6850e6)

I know this isn't the right place for it, but let me say that I'm extremely grateful for this project you've undertaken. I'm a huge fan of open source and look forward to being involved.

**Comment by kalendar** [comment]
Vance, I tried this from another device and it worked. Sorry for the distraction.
