### ISSUE TITLE
[Android] increase max rx sample rate multiplier

### ISSUE THREAD

**Issue by VanceVagell** [VanceVagell/kv4p-ht#141]
It's currently 1.5 max (1.00494 default) and at least one community member found that 1.5 helped. Going higher might help even more.

**Comment by dkaukov** [comment]
Hi @VanceVagell, thank you for your work. As I underrstand, the `rate multiplier` needed to compensate clock differnce betwenn esp32 and Android.  May this be related to those tickets https://github.com/VanceVagell/kv4p-ht/issues/140 and https://github.com/VanceVagell/kv4p-ht/issues/139 ?

**Comment by VanceVagell** [comment]
Since the core issue was resolved, this idea is now obsolete (and this setting no longer exists).
