### ISSUE TITLE
[PCB] Apply RF best practices to the PCB design

### ISSUE THREAD

**Issue by VanceVagell** [VanceVagell/kv4p-ht#20]
Improve my existing PCB design, I'm very amateur at PCB layout. I think there may be an impedence mismatch going to the antenna and I don't think I have enough stitching with the ground plane (among other things!)

**Comment by SmittyHalibut** [comment]
I provided some comments in https://github.com/VanceVagell/kv4p-ht/pull/50 on laying out the filter.

**Comment by SmittyHalibut** [comment]
Done in #86.  Resolve please (it won't let me.)
