### ISSUE TITLE
meshtastic bridging?

### ISSUE THREAD

**Issue by philosiraptor** [VanceVagell/kv4p-ht#28]
would be really cool if we could use the serial interface with a new pcb to talk to a heltec tracker and bridge a meshtastic channel over aprs or vice versa, effectively knitting those two message schemes together

**Comment by VanceVagell** [comment]
Thanks for the idea! At this time there are no plans for meshtastic integration, so I'm going to close this out, but others have raised ideas similar to this so we might come back to this in the future. Feel free to discuss it in the Discord and see if there's strong interest. Reopen this with more details about exactly what you're hoping for if you think there's something here we should reconsider.
