### ISSUE TITLE
[Android] Implement ability to send APRS location messages

### ISSUE THREAD

**Issue by VanceVagell** [VanceVagell/kv4p-ht#5]
Add icon to text chat mode to let user transmit a location APRS message (one-off, not constantly), and on receiving app display this as a clickable link (will open in Google Maps).

If you're implementing this, please ask me for a UX design for the UI details.

**Comment by pweichsel** [comment]
Fully agree with having APRS extended for location message, however an option for regularly send location message may be nice, ideally including some degression algo - if you don’t move, cadence is reduced - similar to the very nice way Kenwood TH-D74 is working. We have used these features during Fielddays and Emcomm exercises in DE with VGC VR-N76, the Kenwoods and some smaller devices such as PicoAPRS, however in combination with the phone UI, we could have a map showing where other OMs are around you. I am not the Android UX guy, but would be happy to contribute to service definition and the APRS protocol part here - 73, DG1KW, Peter

**Comment by DrFrankReade** [comment]
I second a request for this feature - even something as simple as a button in the text screen to send the current position once would be an excellent addition.

**Comment by VanceVagell** [comment]
This is implemented and will be in the next release, v1.6.x
