### ISSUE TITLE
[ESP32] add GET_VERSION command

### ISSUE THREAD

**Issue by VegaDeftwing** [VanceVagell/kv4p-ht#52]
> The ESP32 app needs to report (probably in response to GET_VERSION)

This is probably worth making a separate issue and doing sooner rather than later...

_Originally posted by @VegaDeftwing in https://github.com/VanceVagell/kv4p-ht/issues/22#issuecomment-2429977258_

**Comment by VanceVagell** [comment]
The ESP32 firmware already has this.
