### ISSUE TITLE
[PCB] Add extra LED(s)

### ISSUE THREAD

**Issue by VegaDeftwing** [VanceVagell/kv4p-ht#54]
Copied from discord

> I made an issue (#51) for the using the LED for error handling, probably worth discussing if more LEDs or an RGB LED (or multiple) should be added to the board. They should be low BOM cost. May be able to put two footprints down - one through hole - and just DNP the surface mount one to make it optionally stick through the case, too.
> 
> or light pipes, which are also reasonably cheap. It's not like there's much you'd want to show on the LED anyway, so a single RGB would probably be enough?
> 
> spitballing the utility here: On ititial power on make it red until it's established a data connection, at which point make it green until the first command is rx'd. This would help ID power only USB-C cables
> 
> Then, use a single color for TX indication, lets say red.
> 
> error patterns would probably be distinct enough from any normal TX pattern that it would be fine to reuse the color. This might make a bi-polar 2-color LED an option or just 2 LEDs too, but I'd imagine a singular RGB would actually be cheaper.
> 
> I don't know if any of that is worth the added complexity, since I know minimalism is a goal here.

**Comment by VegaDeftwing** [comment]
This may relate to #1 to be sure that the pins are still accessible on other boards.

**Comment by SmittyHalibut** [comment]
I'll add this in the work I'm doing.  See #63

**Comment by Bakermonitor1932** [comment]
RGB smd mount and header pin breakout for relocating to another location with strip light or a discrete version.

**Comment by SmittyHalibut** [comment]
Fun Fact:  All the Neopixel style RGB LEDs are spec'd for 5v power, even if they're 3.3v tolerant on the data line.

I have used WS2812s successfully on 3x AAA batteries, even after the batteries sag, so probably closer to 3.7 to 4v.

I'll put a WS2812 on this board to test how well it does.  I'll also jumper it so it can be powered from the Vin on the ESP32, but Vin is only available on one of the two ESP32 variants (the other one, Vin is one of the pins hanging off the bottom of the board.)

I'll also put a normal 0805 diode outline on the data pin so if the WS2812 doesn't work out, we can easily swap it out for a single color LED.

**Comment by SmittyHalibut** [comment]
I'm doing away with the dev boards, and putting USB-C directly on our board.  See #63 

This means we'll definitely have access to 5v, which makes this a lot easier.

**Comment by SmittyHalibut** [comment]
This is done in #86.
