### ISSUE TITLE
[Android & ESP32] Allow specifying frequencies to 4 decimal places, not just 3

### ISSUE THREAD

**Issue by VanceVagell** [VanceVagell/kv4p-ht#70]
Some areas use repeaters on frequencies that require the 4th decimal of precision (e.g. 145.7375).

Right now kv4p HT limits frequency to xxx.xxx format, but it should instead use xxx.xxxx.

This will require a change to the message format between Android and ESP32 apps as well, so the Android app needs to send it in the format the version of the ESP32 app expects (version 1 should use xxx.xxx and higher should use xxx.xxxx).

**Comment by adoeller** [comment]
Does the app support repeater offset?

**Comment by VanceVagell** [comment]
This was fixed in V1.1
