### ISSUE TITLE
[Android] Add keep awake setting

### ISSUE THREAD

**Issue by chengmania** [VanceVagell/kv4p-ht#76]
Adding an option for the app the keep the screen awake

**Comment by VanceVagell** [comment]
Thanks for the idea! This would be easy to do, in fact I'm already using this in the firmware update screen (which requires the device to stay on or it fails to flash).

Just need a global setting, and then toggle this Android app setting on/off to match it in each view.

**Comment by VanceVagell** [comment]
Rather than a setting, the app will just keep the screen on while open, unless the user manually turns it off with their power button. To avoid adding yet another setting.
