### ISSUE TITLE
support more usb device

### ISSUE THREAD

**Issue by jumbo5566** [VanceVagell/kv4p-ht#77]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <usb-device vendor-id="1027" product-id="0" /> 
    <usb-device vendor-id="1027" product-id="24577" /> 
    <usb-device vendor-id="1027" product-id="24592" /> 
    <usb-device vendor-id="1027" product-id="24593" /> 
    <usb-device vendor-id="1027" product-id="24596" /> 
    <usb-device vendor-id="1027" product-id="24597" /> 

    
    <usb-device vendor-id="4292" product-id="60000" /> 
    <usb-device vendor-id="4292" product-id="60016" /> 
    <usb-device vendor-id="4292" product-id="60017" /> 
    
    <usb-device vendor-id="1659" product-id="8963" /> 
    <usb-device vendor-id="1659" product-id="9123" /> 
    <usb-device vendor-id="1659" product-id="9139" /> 
    <usb-device vendor-id="1659" product-id="9155" /> 
    <usb-device vendor-id="1659" product-id="9171" /> 
    <usb-device vendor-id="1659" product-id="9187" /> 
    <usb-device vendor-id="1659" product-id="9203" /> 
    
    <usb-device vendor-id="6790" product-id="21795" /> 
    <usb-device vendor-id="6790" product-id="29987" /> 
    <usb-device vendor-id="6790" product-id="29986" /> 

    
    <usb-device vendor-id="9025" />                   
    <usb-device vendor-id="5824" product-id="1155" /> 
    <usb-device vendor-id="1003" product-id="8260" /> 
    <usb-device vendor-id="7855" product-id="4"    /> 
    <usb-device vendor-id="3368" product-id="516"  /> 
    <usb-device vendor-id="1155" product-id="22336" />
    <usb-device vendor-id="1155" product-id="41804" />
    <usb-device vendor-id="22136" product-id="26505" />
    <usb-device vendor-id="1155" product-id="22322" />
    <usb-device vendor-id="11914" product-id="192"   /> 
    <usb-device vendor-id="0x0c26"  /> 
    <usb-device vendor-id="6790" product-id="21970" /> 
    <usb-device vendor-id="1155" product-id="61441" /> 
</resources>

**Comment by VanceVagell** [comment]
Tracking this in issue #59. I'm not sure that all of these listed USB controllers will actually work with the project, and I haven't seen more than 1 or 2 in the wild. All the ESP32-WROOM modules we've used so far have the CP210x
