### ISSUE TITLE
[ESP32] [Arduino] Compilation error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]

### ISSUE THREAD

**Issue by schroepfer** [VanceVagell/kv4p-ht#78]
Hello,
i use Arduino IDE 2.3.2 and Espressif esp32 3.0.7

At compiling the code for NodeMCU-32S (or Developer-Board)
i get this Error:
"Compilation error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]"
in your code line 110:
`  esp_task_wdt_init(10, true); // Reboot if locked up for a bit
`
Please can you help?

Regards
Juergen

**Comment by VanceVagell** [comment]
Hi Juergen,

That version of the esp32 library is not supported (Espressif removed and broke things we need). Please see the Contribute page on kv4p.com, it has all the exact library versions you should install.
