### ISSUE TITLE
Strange - Compilation error <avr/interrupt.h>

### ISSUE THREAD

**Issue by CEHansen** [VanceVagell/kv4p-ht#79]
c:\Users\claus\OneDrive\Dokumenter\Arduino\libraries\SoftwareSerial-master\SoftwareSerial.cpp:41:10: fatal error: avr/interrupt.h: No such file or directory
   41 | #include <avr/interrupt.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by VanceVagell** [comment]
Hi Claus, can you please confirm you have all the exact Arduino IDE library
versions listed on the Contribute page if kv4p.com?

**Comment by VanceVagell** [comment]
Closing, haven't heard back from @CEHansen
