### ISSUE TITLE
[Android] For US region, Add Rx-only support for NOAA WX signals

### ISSUE THREAD

**Issue by gx1400** [VanceVagell/kv4p-ht#81]
DRA818V Freq Range: 134~174MHz
NiceRf SA818-V Freq Range:134～174MHz

Android app:
- Add Settings for "enable NOAA Wx"
- Add tab or presets for NOAA frequencies (162.400 MHz | 162.425 MHz | 162.450 MHz | 162.475 MHz | 162.500 MHz | 162.525 MHz | 162.550 MHz)
- _Stretch goal:_ Automatically select nearest NOAA station using location services
- Disable APRS, Text messaging, and any other Tx when tuned to Wx

ESP32:
- Allow tuning to Wx freq
- Disable Tx

**Comment by VanceVagell** [comment]
I will likely implement this as allowing the user to tune to any frequency the radio module supports, but only TX within the amateur radio range.
