### ISSUE TITLE
Improvements/ Innovations from Arduino Walkie Talkie project

### ISSUE THREAD

**Issue by SE1995** [VanceVagell/kv4p-ht#85]
Hi, I watched TechMinds videos on this project and found it really interesting. When I saw it I remembered the "Arduino Walkie Talkie" project on Instructables by Dragonbtv.

In his project he used the SR_FRS_2WUS radio module. Although the 2WUS is a 2w UHF module it uses the AT1846s XCVR chip inside and can be forced to operate 136-174, 200-260, 400-520 MHz.

He also used a logic switchable LPF network with monolithic LPF chips from Mini-circuits. As far as I know they can be had from Digikey and Mouser, but I'm not sure if JLBPCB stocks them. He used the LFCN series, specifically LFCN-180, LFCN-225, LFCN-490.

It would be cool to have pads to accommodate the SR_FRS_2WUS, and LFCN chips in the future. Although acquiring the 2WUS is a bit more expensive than acquiring a DRA818...

**Comment by VanceVagell** [comment]
Thanks for the idea! Some phones might not be willing to supply the 4+ watts of power needed to power a higher power radio like that. The original USB spec only allows 500mA @ 5v  (2.5 watts), so I'm trying to stay within that limit to support the largest number of phones possible.

I'll resolve this as not planned right now, but anyone who wants to fork the project and give it a try is welcome to!
