### ISSUE TITLE
Vhf aviation frequencys

### ISSUE THREAD

**Issue by MarkMayerflyer** [VanceVagell/kv4p-ht#93]
Would it be possible to open up the app slightly to include 118-136.975 MHz?
I'm a pilot and it would be very convenient to have this in my bag to be able to tune the airport ATIS.

Bgrs,

Mark

**Comment by MarkMayerflyer** [comment]
Thanks for the feedback, it is much appreciated.

**Comment by VanceVagell** [comment]
Thanks for the idea! As noted, our radio module can't support those frequencies.
